var Json = {
    project:[
        {
            name:'思睿官网页面',
            date:'2015.7',
            detail:'这是第一次做前端时，交给我的任务，负责做公司的官网静态页面以及jquery交互效果。',
            image:['img/x1.png','img/x11.png','img/x12.png','img/x13.png'],
            link:'http://www.sirithink.com/'
        },
        {
            name:'商城静态页面',
            date:'2015.9',
            detail:'在学习前端网页制作时，做的关于商城页面的实战项目，里面有很多可以学习的效果，比如用正则对登陆内容的格式进行验证，商城吸顶盒导航，二级导航等。',
            image:['img/x2.png','img/x21.png','img/x22.png','img/x23.png'],
            link:'暂时没有生成'
        },
        {
            name:'天气查询系统',
            date:'2016.4',
            detail:'利用百度天气提供的api，使用jsonp对数据进行跨域请求，可以查询实时天气，空气质量，相关天气指数等。',
            image:['img/x3.png','img/x31.png','img/x32.png','img/x33.png'],
            link:'weather/index.html'
        },
        {
            name:'简易音乐、视频播放器',
            date:'2015.8',
            detail:' 利用html5里新的api，制作了一个简易音乐播放器和视频播放器，可以随意控制播放时间，声音等',
            image:['img/x4.png','img/x4.png','img/x42.png','img/x43.png'],
            link:'musicPlay/music.html'
        },
		{
            name:'响应式旅游网站',
            date:'2016.5',
            detail:'根据pc端布局样式，利用媒体查询、百分比等布局方式制作出的响应式网站',
            image:['img/x5.png','img/x51.png','img/x52.png','img/x53.png'],
            link:'Responsive/index.html'
        }
        
    ]
};
